# Generated by Django 6.0.5 on 2026-06-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='billing_cycle',
            field=models.CharField(choices=[('termly', 'Termly'), ('monthly', 'Monthly')], default='termly', max_length=10),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='month',
            field=models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True),
        ),
    ]
