# Generated by Django 6.0.5 on 2026-06-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_feestructure_billing_cycle_feestructure_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentconfig',
            name='auto_generate_invoices',
            field=models.BooleanField(default=False, help_text='If enabled, the system will auto-generate monthly invoices on the configured day'),
        ),
        migrations.AddField(
            model_name='paymentconfig',
            name='invoice_generation_day',
            field=models.IntegerField(default=1, help_text='Day of month to generate invoices (1-28 recommended)'),
        ),
    ]
