# Generated by Codex on 2026-06-06

from calendar import monthrange
from datetime import date

from django.db import migrations, models
import django.db.models.deletion


def backfill_invoice_periods(apps, schema_editor):
    FeeInvoice = apps.get_model('fees', 'FeeInvoice')
    AcademicYear = apps.get_model('academics', 'AcademicYear')
    Term = apps.get_model('results', 'Term')

    for invoice in FeeInvoice.objects.select_related('fee_structure', 'school').all():
        issued = invoice.issued_date or date.today()
        period_start = date(issued.year, issued.month, 1)
        period_end = date(issued.year, issued.month, monthrange(issued.year, issued.month)[1])

        academic_year_id = None
        term_id = None
        if invoice.fee_structure_id:
            academic_year_id = invoice.fee_structure.academic_year_id
            term_id = invoice.fee_structure.term_id

        if not academic_year_id:
            year = AcademicYear.objects.filter(
                school_id=invoice.school_id,
                start_date__lte=period_start,
                end_date__gte=period_start,
            ).first()
            academic_year_id = year.id if year else None

        if not term_id and academic_year_id:
            term = Term.objects.filter(
                academic_year_id=academic_year_id,
                start_date__lte=period_start,
                end_date__gte=period_start,
            ).first()
            term_id = term.id if term else None

        invoice.academic_year_id = academic_year_id
        invoice.term_id = term_id
        invoice.billing_month = issued.month
        invoice.billing_year = issued.year
        invoice.billing_period_start = period_start
        invoice.billing_period_end = period_end
        invoice.save(update_fields=[
            'academic_year',
            'term',
            'billing_month',
            'billing_year',
            'billing_period_start',
            'billing_period_end',
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_student_date_of_birth'),
        ('fees', '0003_paymentconfig_auto_generate_invoices_and_more'),
        ('results', '0002_assessmentcomponent_studentresultcomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeinvoice',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_invoices', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='billing_month',
            field=models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='billing_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='billing_period_start',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='billing_year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='term',
            field=models.ForeignKey(blank=True, db_index=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_invoices', to='results.term'),
        ),
        migrations.RunPython(backfill_invoice_periods, migrations.RunPython.noop),
    ]
