# Generated by Django 6.0.5 on 2026-06-06 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_student_date_of_birth'),
        ('fees', '0004_feeinvoice_billing_period'),
        ('schools', '0006_alter_schooluser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeinvoice',
            name='billing_period_end',
        ),
        migrations.AddField(
            model_name='feepayment',
            name='applied_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='StudentCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_credits', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='academics.student')),
            ],
            options={
                'unique_together': {('school', 'student')},
            },
        ),
    ]
