# Generated by Django 6.0.5 on 2026-06-06 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_remove_feeinvoice_billing_period_end_and_more'),
        ('schools', '0007_school_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeinvoice',
            name='is_void',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='replaced_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacements', to='fees.feeinvoice'),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='void_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feeinvoice',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_invoices', to='schools.schooluser'),
        ),
    ]
