# Generated by Django 6.0.5 on 2026-05-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_school_grading_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file (MP4, WebM, etc.', null=True, upload_to='gallery/videos/'),
        ),
    ]
