# Generated by Django 6.0.5 on 2026-06-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_alter_schooluser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='role',
            field=models.CharField(choices=[('headmaster', 'Headmaster'), ('admin', 'School Admin'), ('secretary', 'Secretary'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent'), ('senior', 'Senior')], db_index=True, max_length=20),
        ),
    ]
