# Generated by Django 6.0.5 on 2026-06-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_alter_schooluser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='website',
            field=models.CharField(blank=True, help_text='School public website or URL', max_length=200),
        ),
    ]
